### PR TITLE
Xcorrelation improvements

### PR DESCRIPTION
**Pull request by rgetz**
This improves the workings of the FMCOMMS5.

### CODE REVIEW

**Comment by rgetz** [comment]
Ping. 

If we are going to move to a "every feature change needs a pull request" model - people need to be more prompt on reviewing and commenting on pull requests. 

- Robin

**Comment by dNechita** [comment]
It's been a long time since the request was made. I apologize for this.

**Comment by pcercuei** [comment]
Builds fine on Windows, so OK for me.

**Comment by rgetz** [comment]
Thanks.

Who's responsibility is it to delete the branch? The developer who created the branch, or the person who merged things?

-Robin

**Comment by dNechita** [comment]
I would say that the person who merged the branch.

But the developer who created the branch should expect this. Even if the branch gets deleted the developer will have a local copy of that branch in case suddenly discovers that there is more work to be done to that branch. Or a new branch could be created if additional work is required.

-Dan

**Pull request merged**
