### PR TITLE
Fix warnings

### PR DESCRIPTION
**Pull request by dNechita**
There are no more warnings to be shown when compiling the project.

### CODE REVIEW

**Comment by dNechita** [comment]
These changes are for enhancement issue: #30.

**Comment by rgetz** [comment]
Now that there are no warnings, did we want to add -Werror? To make sure we don't introduce any others?

**Comment by dNechita** [comment]
Yes, that makes sense. I'll add the -Werror flag directly to the master but after the pull request gets merged.

**Comment by rgetz** [comment]
So, we are just waiting on an ack from Paul before this gets merged into master?

-Robin

**Comment by pcercuei** [comment]
Looks OK to me, but please don't add -Werror, otherwise the OSC will never build with MinGW.

**Comment by dNechita** [comment]
Paul removed all warnings that come along with a MinGW compilation so I've added the -Werror flag.

-Dan

**Pull request merged**
